-- SPEC-CHATBOT §5 — clearing logged chat data.
--
-- Companion to schema.sql. That file creates; this one removes. Run by hand in
-- the Supabase SQL editor, the same way, because there is no migration tooling
-- and the service key cannot execute DDL or bulk deletes from the app.
--
-- ============================================================================
-- ⚠️  EVERY DELETE IN THIS FILE IS COMMENTED OUT ON PURPOSE.
--
-- Do NOT paste this whole file the way you paste schema.sql. That one is
-- idempotent and safe to re-run; this one is not, and pasting it wholesale is
-- exactly the accident it is written to prevent. Read a section, uncomment the
-- one statement you want, run that alone.
-- ============================================================================
--
-- What deletes what:
--   * chat_messages.session_id is `on delete cascade`, so deleting a session
--     removes its messages. You never need to delete messages directly.
--   * chat_insights has NO foreign key. It is generated by the /study analyze
--     flow, not tied to any session, so it survives every delete below unless
--     you clear it explicitly (section 5).
--   * Deletes are permanent. There is no soft delete and no backup, and the
--     365-day retention window in schema.sql is a separate concern.

-- ---------------------------------------------------------------------------
-- 1. Look first. Always run this before deleting anything.
-- ---------------------------------------------------------------------------

select
  s.started_at,
  s.entry_path,
  s.signal_kind,
  s.alerted_at,
  count(m.id) as messages,
  (array_agg(m.content order by m.created_at)
     filter (where m.role = 'user'))[1] as first_question
from public.chat_sessions s
left join public.chat_messages m on m.session_id = s.id
group by s.id, s.started_at, s.entry_path, s.signal_kind, s.alerted_at
order by s.started_at desc;

-- Totals, so the numbers before and after are comparable.
select
  (select count(*) from public.chat_sessions) as sessions,
  (select count(*) from public.chat_messages) as messages,
  (select count(*) from public.chat_insights) as insights;

-- ---------------------------------------------------------------------------
-- 2. Clear everything (full reset)
--
-- Use when the logged conversations are all your own testing and you want a
-- clean slate before real traffic. Messages go with the sessions; insights do
-- not, so section 5 is a separate decision.
-- ---------------------------------------------------------------------------

-- delete from public.chat_sessions;

-- ---------------------------------------------------------------------------
-- 3. Clear everything before a date
--
-- The safer default. Keeps anything recent in case a real visitor arrived
-- while you were testing. The bound is exclusive, so this keeps the whole of
-- the date you name.
-- ---------------------------------------------------------------------------

-- delete from public.chat_sessions
-- where started_at < timestamptz '2026-08-23';

-- ---------------------------------------------------------------------------
-- 4. Clear everything except the leads
--
-- Keeps any session where the §7 detector fired, which is the only class of
-- conversation with standing value, and drops the rest. Note this keeps
-- flagged-but-not-emailed sessions too, which is usually what you want: those
-- are the ones that arrived while the alert path was misconfigured.
-- ---------------------------------------------------------------------------

-- delete from public.chat_sessions
-- where signal_kind is null;

-- Or drop named sessions only. Ids come from the /study URL,
-- /study/session/<id>, or from the query in section 1.
--
-- delete from public.chat_sessions
-- where id in (
--   '00000000-0000-0000-0000-000000000000'::uuid,
--   '11111111-1111-1111-1111-111111111111'::uuid
-- );

-- ---------------------------------------------------------------------------
-- 5. Clear generated insights
--
-- Independent of everything above: these are the on-demand analyses from
-- /study/insights (§8), and they do not cascade. Clearing sessions while
-- keeping insights leaves reports describing conversations that no longer
-- exist, which is usually the wrong pairing, so decide this alongside 2 to 4.
-- ---------------------------------------------------------------------------

-- delete from public.chat_insights;

-- ---------------------------------------------------------------------------
-- 6. Optional: restart the message id counter
--
-- Cosmetic only, and valid only when chat_messages is empty. The ids are
-- `generated always as identity`, so they keep climbing after a delete; this
-- makes a fresh start read as one. Nothing depends on these values.
-- ---------------------------------------------------------------------------

-- alter table public.chat_messages alter column id restart with 1;
-- alter table public.chat_insights alter column id restart with 1;

-- ---------------------------------------------------------------------------
-- 7. Confirm
-- ---------------------------------------------------------------------------

select
  (select count(*) from public.chat_sessions) as sessions,
  (select count(*) from public.chat_messages) as messages,
  (select count(*) from public.chat_insights) as insights;
