-- SPEC-CHATBOT §5 — chat logging schema.
--
-- Apply by hand in the Supabase SQL editor. There is no migration tooling for
-- one file (§5); re-running is safe because every statement is guarded.
--
-- Access is server-side only, through the service/secret key. RLS is enabled on
-- every table and NO policy is created, so the anon key can read nothing.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- One row per visitor chat session. `id` is generated by the client
-- (crypto.randomUUID) and kept in sessionStorage — no cookies for visitors.
create table if not exists public.chat_sessions (
  id          uuid primary key,
  started_at  timestamptz not null default now(),
  entry_path  text,
  referrer    text,
  -- HMAC-SHA256(ip, ADMIN_COOKIE_SECRET). Raw IPs are never stored (§5).
  ip_hash     text,
  -- v2.3 (§7): 'handle' | 'intent'. Claimed when contact detection fires, by a
  -- conditional update, which is what caps this at one alert per session.
  signal_kind text,
  -- v2.3 (§5): set ONLY after the mail actually left. Two columns rather than
  -- one so a flagged-but-not-emailed session stays distinguishable in /study.
  alerted_at  timestamptz
);

create table if not exists public.chat_messages (
  id             bigint generated always as identity primary key,
  session_id     uuid not null references public.chat_sessions (id) on delete cascade,
  role           text not null check (role in ('user', 'assistant')),
  content        text not null,
  created_at     timestamptz not null default now(),
  model          text,
  input_tokens   int,
  output_tokens  int,
  -- v2.3 (§6): the humor dial this reply was generated at. Null on user rows
  -- and on every row written before the dials shipped.
  humor          smallint,
  -- v2.4 (§6): the conciseness dial, same rules as humor above.
  conciseness    smallint
);

create table if not exists public.chat_insights (
  id            bigint generated always as identity primary key,
  created_at    timestamptz not null default now(),
  period_start  timestamptz,
  period_end    timestamptz,
  summary_md    text,
  model         text
);

-- ---------------------------------------------------------------------------
-- Indexes — the two rate-limit checks in §7 are each one indexed count query.
-- ---------------------------------------------------------------------------

-- Per-IP window: count recent user messages for sessions sharing an ip_hash.
create index if not exists chat_sessions_ip_hash_idx
  on public.chat_sessions (ip_hash);

create index if not exists chat_messages_session_created_idx
  on public.chat_messages (session_id, created_at desc);

-- Global daily cap: count today's assistant messages.
create index if not exists chat_messages_role_created_idx
  on public.chat_messages (role, created_at desc);

-- Admin session list, newest first (§8).
create index if not exists chat_sessions_started_at_idx
  on public.chat_sessions (started_at desc);

-- ---------------------------------------------------------------------------
-- v2.3 additions. Re-runnable like everything above: `add column if not
-- exists` is what lets an already-applied database catch up without a
-- migration tool (§5).
-- ---------------------------------------------------------------------------

alter table public.chat_messages
  add column if not exists humor smallint;

-- v2.4.
alter table public.chat_messages
  add column if not exists conciseness smallint;

alter table public.chat_sessions
  add column if not exists signal_kind text;

alter table public.chat_sessions
  add column if not exists alerted_at timestamptz;

-- Flagged sessions float to the top of /study (§8). Partial: only a handful of
-- rows ever carry a signal, so the index stays tiny.
create index if not exists chat_sessions_signal_kind_idx
  on public.chat_sessions (signal_kind)
  where signal_kind is not null;

-- Daily alert fuse (§7): count today's sent alerts.
create index if not exists chat_sessions_alerted_at_idx
  on public.chat_sessions (alerted_at desc);

-- ---------------------------------------------------------------------------
-- Row Level Security — enabled with NO policies, so nothing is publicly
-- readable. The service/secret key bypasses RLS; the anon key is never used.
-- ---------------------------------------------------------------------------

alter table public.chat_sessions  enable row level security;
alter table public.chat_messages  enable row level security;
alter table public.chat_insights  enable row level security;

-- Belt and braces: revoke the implicit grants the anon/authenticated roles get.
revoke all on public.chat_sessions  from anon, authenticated;
revoke all on public.chat_messages  from anon, authenticated;
revoke all on public.chat_insights  from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Retention — 365 days for raw transcripts, confirmed by Suyu 2026-08-03
-- (SPEC-CHATBOT §5 defaulted to 180; §10 leaves the period to Suyu).
-- Insights are kept indefinitely.
--
-- Manual cleanup is acceptable for v1 (§5). Run this periodically in the SQL
-- editor. chat_messages cascades from chat_sessions, so deleting the sessions
-- is enough.
-- ---------------------------------------------------------------------------

-- delete from public.chat_sessions where started_at < now() - interval '365 days';
